//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpense
    {
        public int ID { get; set; }
        public string PaidTo { get; set; }
        public string PaidBy { get; set; }
        public decimal PaidAmount { get; set; }
        public int ExpenseReasonID { get; set; }
        public System.DateTime PaidDate { get; set; }
    
        public virtual tblExpenseReason tblExpenseReason { get; set; }
    }
}
