//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHouseOwner
    {
        public int ID { get; set; }
        public int HouseID { get; set; }
        public int OwnerID { get; set; }
        public System.DateTime OwnershipDate { get; set; }
        public System.DateTime SoldDate { get; set; }
        public string Status { get; set; }
    
        public virtual tblHouse tblHouse { get; set; }
        public virtual tblOwner tblOwner { get; set; }
    }
}
