//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHousePayment
    {
        public int ID { get; set; }
        public int HouseID { get; set; }
        public string PayerFullname { get; set; }
        public int PaymentReasonID { get; set; }
        public string PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
    
        public virtual tblHouse tblHouse { get; set; }
        public virtual tblPaymentReason tblPaymentReason { get; set; }
    }
}
