//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOwner()
        {
            this.tblHouseOwners = new HashSet<tblHouseOwner>();
        }
    
        public int ID { get; set; }
        public string Fullname { get; set; }
        public int GenderID { get; set; }
        public string CompleteAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public int MaritalStatusID { get; set; }
        public System.DateTime BirthDate { get; set; }
    
        public virtual tblGender tblGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHouseOwner> tblHouseOwners { get; set; }
        public virtual tblMaritalStatu tblMaritalStatu { get; set; }
    }
}
